[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unstable_gym"
version = "2025.04.0"
dependencies = [
    "gymnasium",
    "numpy"
]
requires-python = ">=3.11"
authors = [
  {name = "Taekyung Kim", email = "tkkim.robot@gmail.com"},
]
description = "A gym-like classical control benchmark for evaluating the robustnesses of control and reinforcement learning algorithms."
